#!/usr/bin/env python3
"""Build the projected task-IL CIFAR-10N release artifacts from saved CSVs."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS = ROOT / "results" / "projected_taskil_cifar10n"
METHOD_ORDER = ["er", "derpp", "gate_loss", "gate_conf", "oracle"]
METHOD_NAME = {
    "er": "ER",
    "derpp": "DER++",
    "gate_loss": "Small-loss",
    "gate_conf": "Confidence",
    "oracle": "Oracle",
}
CONDITION_NAME = {
    "c10n_aggre": r"Aggregate ($\approx$9\%)",
    "c10n_worse": r"Worst ($\approx$40\%)",
}
METRICS = [
    "average_accuracy",
    "mean_forgetting",
    "buffer_purity",
    "gate_separation",
    "inversion_rate",
]


def fmt(mean: float, sd: float, bold: bool = False) -> str:
    if not np.isfinite(mean):
        return "--"
    value = f"{mean:.3f}\\pm{sd:.3f}"
    return rf"$\mathbf{{{value}}}$" if bold else rf"${value}$"


def build_table(summary: pd.DataFrame) -> str:
    best = (
        summary[summary.method != "oracle"]
        .sort_values("average_accuracy_mean", ascending=False)
        .groupby("condition", as_index=False)
        .first()
        .set_index("condition")
        .method.to_dict()
    )
    lines = [
        "% Auto-generated by scripts/build_projected_taskil_cifar10n_artifacts.py.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Projected task-IL CIFAR-10N with ResNet-18 over five seeds. Values are mean $\pm$ sample SD. Tasks use binary local heads and preserve the CIFAR-10N correctness mask while projecting every incorrect target to the other local class. All runs use 2,500 training examples per task. Gate separation is the final-task value; the best realizable accuracy is bold.}",
        r"\label{tab:projected_taskil_cifar10n}",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"Noise & Method & Accuracy & Forgetting & Buffer purity & Final gate sep. & Inversion rate \\",
        r"\midrule",
    ]
    conditions = ["c10n_aggre", "c10n_worse"]
    for condition_index, condition in enumerate(conditions):
        condition_rows = summary[summary.condition == condition].set_index("method")
        for method_index, method in enumerate(METHOD_ORDER):
            row = condition_rows.loc[method]
            prefix = (
                rf"\multirow{{5}}{{*}}{{{CONDITION_NAME[condition]}}} & "
                if method_index == 0
                else " & "
            )
            cells = [
                METHOD_NAME[method],
                fmt(
                    row.average_accuracy_mean,
                    row.average_accuracy_sd,
                    bold=method == best[condition],
                ),
                fmt(row.mean_forgetting_mean, row.mean_forgetting_sd),
                fmt(row.buffer_purity_mean, row.buffer_purity_sd),
                fmt(row.gate_separation_mean, row.gate_separation_sd),
                fmt(row.inversion_rate_mean, row.inversion_rate_sd),
            ]
            lines.append(prefix + " & ".join(cells) + r" \\")
        if condition_index == 0:
            lines.append(r"\midrule")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_RESULTS / "csv" / "final_metrics.csv",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_RESULTS)
    args = parser.parse_args()

    data = pd.read_csv(args.input)
    data = data[
        data.benchmark.eq("cifar10n_taskil")
        & data.condition.isin(CONDITION_NAME)
        & data.method.isin(METHOD_ORDER)
    ].copy()
    expected_cells = len(CONDITION_NAME) * len(METHOD_ORDER)
    counts = data.groupby(["condition", "method"]).seed.nunique()
    if len(data) != 50 or len(counts) != expected_cells or not counts.eq(5).all():
        raise SystemExit("Expected 10 complete five-seed bridge cells (50 rows).")

    per_seed_columns = [
        "run_id",
        "condition",
        "noise_rate",
        "method",
        "seed",
        *METRICS,
        "total_time_s",
    ]
    per_seed = data[per_seed_columns].sort_values(["condition", "method", "seed"])

    grouped = data.groupby(["condition", "method"], sort=False)[METRICS]
    summary = grouped.agg(["mean", "std"])
    summary.columns = [
        f"{metric}_{'sd' if stat == 'std' else stat}"
        for metric, stat in summary.columns
    ]
    summary = summary.reset_index()
    summary["n_seeds"] = 5
    summary["method_order"] = summary.method.map(METHOD_ORDER.index)
    summary = summary.sort_values(["condition", "method_order"]).drop(
        columns="method_order"
    )

    args.output.mkdir(parents=True, exist_ok=True)
    per_seed.to_csv(args.output / "per_seed_metrics.csv", index=False)
    summary.to_csv(args.output / "summary_mean_sd.csv", index=False)
    (args.output / "table_projected_taskil_cifar10n.tex").write_text(
        build_table(summary), encoding="utf-8"
    )
    print(f"Wrote bridge artifacts to {args.output}")


if __name__ == "__main__":
    main()
