#!/usr/bin/env python3
"""Build seed-paired uncertainty summaries for the manuscript CIFAR claims."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "results" / "neural_networks_submission" / "csv" / "final_metrics.csv"
DEFAULT_CONFIGS = ROOT / "results" / "neural_networks_submission" / "configs"
DEFAULT_OUTPUT = ROOT / "results" / "paired_uncertainty"


@dataclass(frozen=True)
class Comparison:
    benchmark: str
    condition: str
    left: str
    right: str
    metric: str
    benchmark_name: str
    condition_name: str
    comparison_name: str


COMPARISONS = [
    Comparison("split_cifar10", "sym20", "gate_loss", "er", "average_accuracy", "Split-CIFAR-10", r"Sym. 20\%", "Small-loss $-$ ER (accuracy)"),
    Comparison("split_cifar10", "sym60", "gate_loss", "er", "average_accuracy", "Split-CIFAR-10", r"Sym. 60\%", "Small-loss $-$ ER (accuracy)"),
    Comparison("split_cifar10", "sym20", "oracle", "gate_loss", "average_accuracy", "Split-CIFAR-10", r"Sym. 20\%", "Oracle $-$ Small-loss (accuracy)"),
    Comparison("split_cifar10", "sym60", "oracle", "er", "average_accuracy", "Split-CIFAR-10", r"Sym. 60\%", "Oracle $-$ ER (accuracy)"),
    Comparison("split_cifar10", "asym40", "oracle", "gate_loss", "average_accuracy", "Split-CIFAR-10", r"Asym. 40\%", "Oracle $-$ Small-loss (accuracy)"),
    Comparison("seq_cifar10", "sym20", "oracle", "derpp", "average_accuracy", "Seq-CIFAR-10", r"Sym. 20\%", "Oracle $-$ DER++ (accuracy)"),
    Comparison("seq_cifar10", "sym60", "oracle", "gate_loss", "average_accuracy", "Seq-CIFAR-10", r"Sym. 60\%", "Oracle $-$ Small-loss (accuracy)"),
    Comparison("seq_cifar10", "asym40", "oracle", "derpp", "average_accuracy", "Seq-CIFAR-10", r"Asym. 40\%", "Oracle $-$ DER++ (accuracy)"),
    Comparison("seq_cifar10", "sym20", "gate_loss", "er", "buffer_purity", "Seq-CIFAR-10", r"Sym. 20\%", "Small-loss $-$ ER (buffer purity)"),
    Comparison("seq_cifar10", "sym20", "gate_loss", "er", "average_accuracy", "Seq-CIFAR-10", r"Sym. 20\%", "Small-loss $-$ ER (accuracy)"),
    Comparison("seq_cifar10", "sym60", "gate_loss", "er", "buffer_purity", "Seq-CIFAR-10", r"Sym. 60\%", "Small-loss $-$ ER (buffer purity)"),
    Comparison("seq_cifar10", "sym60", "gate_loss", "er", "average_accuracy", "Seq-CIFAR-10", r"Sym. 60\%", "Small-loss $-$ ER (accuracy)"),
]


def budget(run_id: str, config_root: Path) -> int:
    path = config_root / f"{run_id}.json"
    if not path.exists():
        raise FileNotFoundError(f"Missing frozen run configuration: {path}")
    config = json.loads(path.read_text(encoding="utf-8"))
    return int(config["data"]["max_train_per_task"])


def paired_values(data: pd.DataFrame, comparison: Comparison) -> pd.DataFrame:
    base = data[
        data.benchmark.eq(comparison.benchmark)
        & data.condition.eq(comparison.condition)
    ]
    left = base[base.method.eq(comparison.left)][
        ["run_id", "seed", comparison.metric]
    ].rename(columns={"run_id": "left_run_id", comparison.metric: "left_value"})
    right = base[base.method.eq(comparison.right)][
        ["run_id", "seed", comparison.metric]
    ].rename(columns={"run_id": "right_run_id", comparison.metric: "right_value"})
    paired = left.merge(right, on="seed", validate="one_to_one").sort_values("seed")
    if len(paired) != 5 or set(paired.seed) != set(range(5)):
        raise ValueError(f"Incomplete five-seed comparison: {comparison}")
    paired["difference"] = paired.left_value - paired.right_value
    return paired


def bootstrap_ci(values: np.ndarray, seed: int) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    indices = rng.integers(0, len(values), size=(10_000, len(values)))
    means = values[indices].mean(axis=1)
    low, high = np.percentile(means, [2.5, 97.5])
    return float(low), float(high)


def build_table(summary: pd.DataFrame) -> str:
    lines = [
        "% Auto-generated by scripts/build_paired_cifar_uncertainty.py.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Seed-paired uncertainty for the principal CIFAR claims. Each row reports the within-seed mean difference, a percentile-bootstrap $95\%$ interval with $10{,}000$ resamples, paired Cohen's $d_z$, and the two-sided exact Wilcoxon $p$-value. With five nonzero pairs the smallest attainable Wilcoxon $p$-value is $0.0625$. Seeds 0--2 use 1,500 examples per task and seeds 3--4 use 2,500; both methods in every pair use the same seed-specific budget.}",
        r"\label{tab:paired_ci}",
        r"\small",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{lllcccc}",
        r"\toprule",
        r"Benchmark & Condition & Comparison (metric) & $\Delta$ & $95\%$ CI & $d_z$ & Wilcoxon $p$ \\",
        r"\midrule",
    ]
    for row in summary.itertuples(index=False):
        lines.append(
            f"{row.benchmark_name} & {row.condition_name} & {row.comparison_name} & "
            rf"${row.mean_difference:+.3f}$ & "
            rf"$[{row.ci_low:+.3f},\,{row.ci_high:+.3f}]$ & "
            rf"${row.cohens_dz:+.2f}$ & ${row.wilcoxon_p:.3f}$ \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--configs", type=Path, default=DEFAULT_CONFIGS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    data = pd.read_csv(args.input)
    difference_rows: list[dict] = []
    summary_rows: list[dict] = []
    for index, comparison in enumerate(COMPARISONS):
        paired = paired_values(data, comparison)
        paired["left_budget"] = paired.left_run_id.map(lambda value: budget(value, args.configs))
        paired["right_budget"] = paired.right_run_id.map(lambda value: budget(value, args.configs))
        if not (paired.left_budget == paired.right_budget).all():
            raise ValueError(f"Unmatched seed budgets: {comparison}")
        values = paired.difference.to_numpy(dtype=float)
        low, high = bootstrap_ci(values, seed=20260628 + index)
        sd = values.std(ddof=1)
        test = wilcoxon(values, alternative="two-sided", method="exact")
        comparison_id = f"comparison_{index + 1:02d}"
        for row in paired.itertuples(index=False):
            difference_rows.append(
                {
                    "comparison_id": comparison_id,
                    "benchmark": comparison.benchmark,
                    "condition": comparison.condition,
                    "left_method": comparison.left,
                    "right_method": comparison.right,
                    "metric": comparison.metric,
                    "seed": row.seed,
                    "max_train_per_task": row.left_budget,
                    "left_value": row.left_value,
                    "right_value": row.right_value,
                    "difference": row.difference,
                    "left_run_id": row.left_run_id,
                    "right_run_id": row.right_run_id,
                }
            )
        summary_rows.append(
            {
                "comparison_id": comparison_id,
                "benchmark": comparison.benchmark,
                "condition": comparison.condition,
                "left_method": comparison.left,
                "right_method": comparison.right,
                "metric": comparison.metric,
                "n_pairs": len(values),
                "mean_difference": values.mean(),
                "ci_low": low,
                "ci_high": high,
                "cohens_dz": values.mean() / sd,
                "wilcoxon_p": float(test.pvalue),
                "benchmark_name": comparison.benchmark_name,
                "condition_name": comparison.condition_name,
                "comparison_name": comparison.comparison_name,
            }
        )

    differences = pd.DataFrame(difference_rows)
    summary = pd.DataFrame(summary_rows)
    args.output.mkdir(parents=True, exist_ok=True)
    differences.to_csv(args.output / "per_seed_differences.csv", index=False)
    summary.to_csv(args.output / "paired_summary.csv", index=False)
    (args.output / "table_paired_cifar_claims.tex").write_text(
        build_table(summary), encoding="utf-8"
    )
    print(f"Wrote paired uncertainty artifacts to {args.output}")


if __name__ == "__main__":
    main()
